#include <cstdint>

extern const unsigned int impsy_models_musicMDRNN_dim4_layers2_units32_mixtures5_scale10_tflite_len;
extern const unsigned char impsy_models_musicMDRNN_dim4_layers2_units32_mixtures5_scale10_tflite[];
